### ISSUE TITLE
Move build artefacts to a target folder

### ISSUE THREAD

**Issue by FrankR85** [mmitch/cobol-travis#2]
Would be great if we could move all artefacts that are created during the ```make``` to a ```target``` subfolder.

Maven-like. :monkey:

**Comment by mmitch** [comment]
Is that one central ``target`` directory for all subprojects?
Or one ``target`` dirctory per subproject?

Given this input structure, what should the output look like?

```
cobol
   helloworld
      src
         helloworld.cbl
      test
         addition.cbl
   calculator
      src
         calculator.cbl
         calculator-up.cbl
      test
         addition.cbl
         subtraction.cbl
         input.cbl
```

**Comment by FrankR85** [comment]
Actually I think that this folder structure is indeed a new feature that we might not need _immediately_.

For our purposes it would be sufficent to support one project folder. Either ```helloworld``` or ```calculator```. But not both projects in one repository.

If we want to support multiple projects in one repository, I would suggest to have ```target```-folder for each project.

The main idea behind this issue is to be able to exclude the build artefacts from source control via an entry in ```.gitignore```. For this purpose the concrete folder structure is not that important as long as all artefacts are in a folder named ```target```.

**Comment by mmitch** [comment]
We already have mupltiple source folders *for free* since day 1 ;-)

One ``target/`` directory per source folder is the easiest way to go, so I'll do that.
