### ISSUE TITLE
Support testing of subprograms

### ISSUE THREAD

**Issue by FrankR85** [mmitch/cobol-travis#3]
The testing framework supports[ testing of subprograms](https://github.com/neopragma/cobol-unit-test/wiki/03.-Usage-guide#testing-a-subprogram).

If we also want to support this with ```make``` we need some modifications:

- The driver program has to be provided by the user. The makefile needs to know what file is the driver program and compile it with ```cobc -x```.
- When running the tests, not the module-under-test has to be invoked, but the driver program. This is abstracted away by the ```-s``` parameter in the original ```run-ut``` script.
- The module-under-test must not be compiled with ```cobc -x```but with ```cobc -m``` instead, because the resulting object should be a loadable module.

**Comment by mmitch** [comment]
see ``cobol/static_call/test`` for an example
