### ISSUE TITLE
source file extension

### ISSUE THREAD

**Issue by mmitch** [mmitch/cobol-travis#7]
@FrankR85 What is the proper souce file extension for COBOL code?

We currently use ``.cbl``, but the OpenCobol documentation uses ``.cob``: [example](https://open-cobol.sourceforge.io/historical/open-cobol/Static-Linking.html#Static%20Linking)

**Comment by FrankR85** [comment]
There is no semantic difference between ```.cbl``` and ```.cob```[as far as I know](https://open-cobol.sourceforge.io/doc/gnucobol.html#Build-target).

So I suggest we stick with ```.cbl```.

**Comment by mmitch** [comment]
So we stick with both :-)
Actually the build system currently is totally agnostic to the file extension. Whatever is listed in ``build.txt`` will be built – of course ``cobc`` must understand it, so we can have both ``.cbl`` and ``.cob`` (or even ``.c``).
